name: Latest projects workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-projects:
    name: Update this repo's README with latest projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "PROJECTS"
          feed_list: "https://mattstruble.com/feed/projects.xml"